### ISSUE TITLE
predix SSO fedration

### ISSUE THREAD

**Issue by shoaib30** [PredixDev/cf-predix#4]
Since Jan 2018, Predix has shifted to SSO login for internal GE developers. The plugin uses the old login method with email and password only.

We should have an option to use SSO login through the plugin 
    `cf predix --sso`

which would internally call
`cf login --sso`

**Comment by gstroup** [comment]
This plugin is no longer being supported.  We've moved to a wrapper around the CF CLI instead.  You can install the Predix CLI here, which supports the --sso option:

https://github.com/predixdev/predix-cli
